#############################################################################
# Makefile for building: BufferSink
# Generated by qmake (3.0) (Qt 5.3.2)
# Project:  SourceBuffer.pro
# Template: app
# Command: C:\Qt\Static\5.3.2\bin\qmake.exe -spec win32-g++ -o Makefile SourceBuffer.pro
#############################################################################

MAKEFILE      = Makefile

first: debug
install: debug-install
uninstall: debug-uninstall
QMAKE         = C:\Qt\Static\5.3.2\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = copy /y
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		debug \
		release


debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: SourceBuffer.pro ../../../Qt/Static/5.3.2/mkspecs/win32-g++/qmake.conf ../../../Qt/Static/5.3.2/mkspecs/features/spec_pre.prf \
		../../../Qt/Static/5.3.2/mkspecs/qdevice.pri \
		../../../Qt/Static/5.3.2/mkspecs/features/device_config.prf \
		../../../Qt/Static/5.3.2/mkspecs/common/shell-win32.conf \
		../../../Qt/Static/5.3.2/mkspecs/qconfig.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_axbase.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_axbase_private.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_axcontainer.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_axcontainer_private.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_axserver.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_axserver_private.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_plugin_qdds.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_plugin_qicns.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_plugin_qico.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_plugin_qjp2.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_plugin_qminimal.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_plugin_qmldbg_qtquick2.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_plugin_qmng.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_plugin_qnativewifibearer.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_plugin_qoffscreen.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_plugin_qsvg.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_plugin_qsvgicon.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_plugin_qtaccessiblequick.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_plugin_qtaccessiblewidgets.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_plugin_qtga.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_plugin_qtiff.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_plugin_qwbmp.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_plugin_qwebp.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_plugin_qwindows.pri \
		../../../Qt/Static/5.3.2/mkspecs/modules/qt_plugin_windowsprintersupport.pri \
		../../../Qt/Static/5.3.2/mkspecs/features/qt_functions.prf \
		../../../Qt/Static/5.3.2/mkspecs/features/qt_config.prf \
		../../../Qt/Static/5.3.2/mkspecs/features/win32/qt_config.prf \
		../../../Qt/Static/5.3.2/mkspecs/win32-g++/qmake.conf \
		../../../Qt/Static/5.3.2/mkspecs/features/spec_post.prf \
		../../../Qt/Static/5.3.2/mkspecs/features/exclusive_builds.prf \
		../../../Qt/Static/5.3.2/mkspecs/features/default_pre.prf \
		../../../Qt/Static/5.3.2/mkspecs/features/win32/default_pre.prf \
		../../../Qt/Static/5.3.2/mkspecs/features/resolve_config.prf \
		../../../Qt/Static/5.3.2/mkspecs/features/exclusive_builds_post.prf \
		../../../Qt/Static/5.3.2/mkspecs/features/default_post.prf \
		../../../Qt/Static/5.3.2/mkspecs/features/win32/console.prf \
		../../../Qt/Static/5.3.2/mkspecs/features/c++11.prf \
		../../../Qt/Static/5.3.2/mkspecs/features/win32/rtti.prf \
		../../../Qt/Static/5.3.2/mkspecs/features/precompile_header.prf \
		../../../Qt/Static/5.3.2/mkspecs/features/warn_on.prf \
		../../../Qt/Static/5.3.2/mkspecs/features/qt.prf \
		../../../Qt/Static/5.3.2/mkspecs/features/resources.prf \
		../../../Qt/Static/5.3.2/mkspecs/features/moc.prf \
		../../../Qt/Static/5.3.2/mkspecs/features/testcase_targets.prf \
		../../../Qt/Static/5.3.2/mkspecs/features/exceptions.prf \
		../../../Qt/Static/5.3.2/mkspecs/features/yacc.prf \
		../../../Qt/Static/5.3.2/mkspecs/features/lex.prf \
		SourceBuffer.pro \
		C:/Qt/Static/5.3.2/lib/Qt5Core.prl
	$(QMAKE) -spec win32-g++ -o Makefile SourceBuffer.pro
..\..\..\Qt\Static\5.3.2\mkspecs\features\spec_pre.prf:
..\..\..\Qt\Static\5.3.2\mkspecs\qdevice.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\features\device_config.prf:
..\..\..\Qt\Static\5.3.2\mkspecs\common\shell-win32.conf:
..\..\..\Qt\Static\5.3.2\mkspecs\qconfig.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_axbase.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_axbase_private.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_axcontainer.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_axcontainer_private.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_axserver.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_axserver_private.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_bootstrap_private.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_concurrent.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_concurrent_private.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_core.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_core_private.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_gui.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_gui_private.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_network.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_network_private.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_opengl.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_opengl_private.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_openglextensions.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_openglextensions_private.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_platformsupport_private.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_printsupport.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_printsupport_private.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_qml.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_qml_private.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_qmldevtools_private.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_qmltest.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_qmltest_private.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_quick.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_quick_private.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_quickparticles_private.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_quickwidgets.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_quickwidgets_private.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_serialport.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_serialport_private.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_sql.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_sql_private.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_svg.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_svg_private.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_testlib.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_testlib_private.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_widgets.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_widgets_private.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_xml.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_xml_private.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_xmlpatterns.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_plugin_qdds.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_plugin_qgenericbearer.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_plugin_qicns.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_plugin_qico.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_plugin_qjp2.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_plugin_qminimal.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_plugin_qmldbg_qtquick2.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_plugin_qmldbg_tcp.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_plugin_qmng.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_plugin_qnativewifibearer.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_plugin_qoffscreen.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_plugin_qsvg.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_plugin_qsvgicon.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_plugin_qtaccessiblequick.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_plugin_qtaccessiblewidgets.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_plugin_qtga.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_plugin_qtiff.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_plugin_qwbmp.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_plugin_qwebp.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_plugin_qwindows.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\modules\qt_plugin_windowsprintersupport.pri:
..\..\..\Qt\Static\5.3.2\mkspecs\features\qt_functions.prf:
..\..\..\Qt\Static\5.3.2\mkspecs\features\qt_config.prf:
..\..\..\Qt\Static\5.3.2\mkspecs\features\win32\qt_config.prf:
..\..\..\Qt\Static\5.3.2\mkspecs\win32-g++\qmake.conf:
..\..\..\Qt\Static\5.3.2\mkspecs\features\spec_post.prf:
..\..\..\Qt\Static\5.3.2\mkspecs\features\exclusive_builds.prf:
..\..\..\Qt\Static\5.3.2\mkspecs\features\default_pre.prf:
..\..\..\Qt\Static\5.3.2\mkspecs\features\win32\default_pre.prf:
..\..\..\Qt\Static\5.3.2\mkspecs\features\resolve_config.prf:
..\..\..\Qt\Static\5.3.2\mkspecs\features\exclusive_builds_post.prf:
..\..\..\Qt\Static\5.3.2\mkspecs\features\default_post.prf:
..\..\..\Qt\Static\5.3.2\mkspecs\features\win32\console.prf:
..\..\..\Qt\Static\5.3.2\mkspecs\features\c++11.prf:
..\..\..\Qt\Static\5.3.2\mkspecs\features\win32\rtti.prf:
..\..\..\Qt\Static\5.3.2\mkspecs\features\precompile_header.prf:
..\..\..\Qt\Static\5.3.2\mkspecs\features\warn_on.prf:
..\..\..\Qt\Static\5.3.2\mkspecs\features\qt.prf:
..\..\..\Qt\Static\5.3.2\mkspecs\features\resources.prf:
..\..\..\Qt\Static\5.3.2\mkspecs\features\moc.prf:
..\..\..\Qt\Static\5.3.2\mkspecs\features\testcase_targets.prf:
..\..\..\Qt\Static\5.3.2\mkspecs\features\exceptions.prf:
..\..\..\Qt\Static\5.3.2\mkspecs\features\yacc.prf:
..\..\..\Qt\Static\5.3.2\mkspecs\features\lex.prf:
SourceBuffer.pro:
C:/Qt/Static/5.3.2/lib/Qt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec win32-g++ -o Makefile SourceBuffer.pro

qmake_all: FORCE

make_first: debug-make_first release-make_first FORCE
all: debug-all release-all FORCE
clean: debug-clean release-clean FORCE
distclean: debug-distclean release-distclean FORCE
	-$(DEL_FILE) Makefile

debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables

check: first
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
